version: 2023.04.26
slug: racksync-cloudflare-tunnel-standard
name: Cloudflare Tunnel
description: Cloudflare Tunnel from RACKSYNC.COM (Zero Trust Migratable)
url: https://github.com/racksync/hass-addons-cloudflared-tunnel
codenotary: devops@racksync.com
ingress: false
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: system
hassio_api: false
boot: auto
host_network: true
apparmor: true
host_pid: true
homeassistant: 2022.11.2
advanced: true
stage: stable
map: 
  - config:ro
  - ssl:ro
options:
  pem: "cert.pem"
  host: ""
  credentials: ""
  url: "127.0.0.1:8123"
  desc: ""
  flag: ""
  no_autoupdate: false

schema:
  pem: str
  host: str
  credentials: str?
  url: str
  desc: str?
  flag: str?
  no_autoupdate: bool
