version: 2022.05.04
slug: racksync-argo-cloudflare
name: Cloudflared Argo Tunnel
description: Cloudflare Argo Tunnel from RACKSYNC.COM
url: https://github.com/racksync/hass-addons-cloudflared-tunnel
codenotary: jack@racksync.com
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: system
hassio_api: false
boot: auto
host_network: true
apparmor: false
map: 
  - config:ro
  - ssl:ro
options:
  pem: "cert.pem"
  host: ""
  url: "localhost:8123"
  name: "your tunnel name"
schema:
  pem: str
  host: str
  url: str
  name: str?
