version: 2022.06.14
slug: racksync-cloudflare-tunnel
name: Cloudflared Argo Tunnel
description: Cloudflare Argo Tunnel from RACKSYNC.COM
url: https://github.com/racksync/hass-addons-cloudflared-tunnel
codenotary: devops@racksync.com
ingress: false
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: system
hassio_api: false
boot: auto
host_network: true
apparmor: false
host_pid: true
map: 
  - config:ro
  - ssl:ro
options:
  pem: "cert.pem"
  host: ""
  credentials: "cred.json"
  url: "127.0.0.1:8123"
  description: ""
  no_autoupdate: false
schema:
  pem: str
  host: str
  credentials: str
  url: str
  description: str?
  no_autoupdate: bool