version: 2022.06.14
slug: racksync-argo-cloudflare-legacy
name: Cloudflared Argo Tunnel (Legacy)
description: Cloudflare Argo Tunnel from RACKSYNC.COM
url: https://github.com/racksync/hass-addons-cloudflared-tunnel
codenotary: jack@racksync.com
ingress: false
init: false
#panel_icon: mdi:security-network
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: system
hassio_api: false
boot: auto
host_network: true
apparmor: false
host_pid: true
map: 
  - config:ro
  - ssl:ro
options:
  pem: "cert.pem"
  host: ""
  url: "127.0.0.1:8123"
  desc: ""
schema:
  pem: str
  host: str
  url: str
  desc: str?
