version: 2022.06.21
slug: racksync-cloudflare-tunnel-standard
name: Cloudflare Tunnel (Standard)
description: Cloudflare Tunnel from RACKSYNC.COM (Zero Trust Migratable)
url: https://github.com/racksync/hass-addons-cloudflared-tunnel
codenotary: devops@racksync.com
ingress: false
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: system
hassio_api: false
boot: auto
host_network: true
apparmor: false
host_pid: true
map: 
  - config:ro
  - ssl:ro
options:
  pem: "cert.pem"
  host: ""
  credentials: ""
  url: "127.0.0.1:8123"
  description: ""
  flag: ""
  no_autoupdate: false
  legacy: false
schema:
  pem: str
  host: str
  credentials: str
  url: str
  description: str?
  flag: str?
  no_autoupdate: bool
  legacy: bool