build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:12.2.3
  amd64: ghcr.io/hassio-addons/base/amd64:12.2.3
  armhf: ghcr.io/hassio-addons/base/armhf:12.2.3
  armv7: ghcr.io/hassio-addons/base/armv7:12.2.3
  i386: ghcr.io/hassio-addons/base/i386:12.2.3
codenotary:
  base_image: codenotary@frenck.dev
  signer: jack@racksync.com