version: 2022.06.14a
slug: racksync-cloudflare-tunnel-legacy
name: Cloudflare Tunnel (Legacy)
description: Cloudflare Tunnel from RACKSYNC.COM (Use it at your own risk!)
url: https://github.com/racksync/hass-addons-cloudflared-tunnel
codenotary: devops@racksync.com
ingress: false
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: system
hassio_api: false
boot: auto
host_network: true
apparmor: false
host_pid: true
map: 
  - config:ro
  - ssl:ro
options:
  pem: "cert.pem"
  host: ""
  url: "127.0.0.1:8123"
  desc: ""
schema:
  pem: str
  host: str
  url: str
  desc: str?
